export const AUTH_TOKEN_GETTER = 'AUTH_TOKEN_GETTER'
export const AUTH_USER_DETAILS_GETTER = 'AUTH_USER_DETAILS_GETTER'
export const AUTH_CREATE_USER_ACTION = 'AUTH_CREATE_USER_ACTION'
export const AUTH_LOGOUT_ACTION = 'AUTH_LOGOUT_ACTION'
export const AUTH_SET_LOGOUT_TIMER = 'AUTH_SET_LOGOUT_TIMER'
export const AUTH_LOGIN_ACTION = 'AUTH_LOGIN_ACTION'
export const AUTH_AUTO_LOGIN_ACTION = 'AUTH_AUTO_LOGIN_ACTION'
export const AUTH_ERROR_GETTER = 'AUTH_ERROR_GETTER'
export const AUTH_AUTHENTICATING_GETTER = 'AUTH_AUTHENTICATING_GETTER'
export const AUTH_START_AUTHENTICATION_ACTION = 'AUTH_START_AUTHENTICATION_ACTION'

export const DATACENTERS_GETTER = 'DATACENTERS_GETTER'
export const DATACENTERS_FETCH_ACTION = 'DATACENTERS_FETCH_ACTION'

export const EXCEPTIONS_GETTER = 'EXCEPTIONS_GETTER'
export const EXCEPTIONS_FETCH_ACTION = 'EXCEPTIONS_FETCH_ACTION'

export const PROCESS_GETTER = 'PROCESS_GETTER'
export const PROCESS_SUMMARY_GETTER = 'PROCESS_SUMMARY_GETTER'
export const PROCESS_FETCHING_GETTER = 'PROCESS_FETCHING_GETTER'
export const PROCESS_GET_ALL_ACTION = 'PROCESS_GET_ALL_ACTION'
export const PROCESS_FETCH_START_ACTION = 'PROCESS_FETCH_START_ACTION'

export const DISK_GETTER = 'DISK_GETTER'
export const DISK_GET_ALL_ACTION = 'DISK_GET_ALL_ACTION'

export const COBRANDS_GETTER = 'COBRANDS_GETTER'
export const COBRANDS_LOADING_STATUS_GETTER = 'COBRANDS_LOADING_STATUS_GETTER'
export const COBRANDS_ERROR_GETTER = 'COBRANDS_ERROR_GETTER'
export const COBRANDS_FETCH_ACTION = 'COBRANDS_FETCH_ACTION'
export const COBRANDS_FETCH_START_ACTION = 'COBRANDS_FETCH_START_ACTION'

export const OUTING_GETTER = 'OUTING_GETTER'
export const OUTING_FETCH_ACTION = 'OUTING_FETCH_ACTION'
export const OUTING_LOADING_STATUS_GETTER = 'OUTING_LOADING_STATUS_GETTER'
export const OUTING_FETCH_START_ACTION = 'OUTING_FETCH_START_ACTION'
export const OUTING_ERROR_GETTER = 'OUTING_ERROR_GETTER'

// export const SCANNER_GET_EXCEPTION_SUMMARY_FOR_COMPONENT = 'SCANNER_GET_EXCEPTION_SUMMARY_FOR_COMPONENT';
// export const SCANNER_GETTER = 'SCANNER_GETTER'
// export const SCANNER_FETCH_ACTION = 'SCANNER_FETCH_ACTION'
